### ISSUE TITLE
Posting reward beneficiaries not converting to integers before OP.

### ISSUE THREAD

**Issue by Tadasu85** [aaroncox/chainbb#20]
Error:
transaction.operations = comment,[object Object],comment_options,[object Object]	 cause: comment_options.extensions = 0,[object Object]	 cause: 0.beneficiaries = [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]	 cause: beneficiaries.weight = 254.99999999999997	 cause: Illegal value: 254.99999999999997 (not an integer) 
 
Reproduction:
Split the rewards on a non integer.

Suggested fix:

Before transaction OP is fired round to the nearest whole number.

Cheers Jesta :)

**Comment by aaroncox** [comment]
Haha good catch. I'll get this fixed in a moment.

**Comment by aaroncox** [comment]
Deploy is running - should be fixed on live in a few moments.

**Comment by Tadasu85** [comment]
Awesome! Thanks man!
