### ISSUE TITLE
Create own forum

### ISSUE THREAD

**Issue by fervi** [aaroncox/chainbb#29]
I think this option should be ;)

When you are on the main page of ChainBB You have subforums like "community", "crypto", etc. I would like to make my own subforums such as "Linux", "Windows", etc. with their own tags - that is to make their own forum.

The best option would eventually appear on ChainBB.
For example, you go to chainbb.com/forum/pingwineknet (or something) and you have a list of subforums that you have set up, etc.

**Comment by aaroncox** [comment]
This is one of the next things I'm working on

**Comment by aaroncox** [comment]
Completed
