### ISSUE TITLE
How to run your own chainbb?

### ISSUE THREAD

**Issue by fervi** [aaroncox/chainbb#30]
Hello. 

I tried to run my own instance of chainbb, but I received something like this:
http://meshnet-users.tk/paste/p/ajzj/p.txt

I don't see on docker compose file any port that can work for ChainBB-fervi. Maybe I do something wrong, but there is no wiki :(

Fervi

**Comment by aaroncox** [comment]
The errors in that log make it look like it can't connect to the steem nodes specified (https://github.com/aaroncox/chainbb/blob/master/services/indexer/steem/main.py#L16-L18). Right now chainBB is expecting a local steemd node to be running on the same machine on port 5090.

As for the frontend app, you have to manually navigate into the `services/frontend` directory and use `npm start`. 

chainBB is still relatively new, so there's no documentation and it's not incredibly easy to run yet.
