### ISSUE TITLE
Don't try to vote if below vote dust threshhold

### ISSUE THREAD

**Issue by syvb** [aaroncox/chainbb#53]
In the Steem source code, if ```abs_rshares > 50000000``` does *not* hold true, then a vote cannot be cast, to avoid low powered votes from spamming the blockchain. ChainBB should display a message, instead of loading on the Vote button forever, if this happens.

**Comment by inertia186** [comment]
Note: https://github.com/steemit/steem/issues/1764

> We are removing the vote dust threshold in HF 20.
